# Generated by Django 2.2.4 on 2019-08-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('isrc', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('spotify_id', models.CharField(default=None, max_length=30)),
                ('apple_music_id', models.CharField(default=None, max_length=30)),
            ],
        ),
    ]
